# -*- coding: utf-8 -*-
"""Análise_Descritiva.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AmfqiDTmd4kkqe-KDDVSmnqDt-O3puSo

***
# <font color=green size=10>CURSO DE ESTATÍSTICA - PARTE 1</font>
***

## Trabalho de Análise Descritiva de um Conjunto de Dados

Utilizando os conhecimentos adquiridos em nosso treinamento realize uma análise descritiva básica de um conjunto de dados retirados da Pesquisa Nacional por Amostra de Domicílios - 2015 do IBGE. 

Vamos construir histogramas, calcular e avaliar medidas de tendência central, medidas separatrizes e de dispersão dos dados.

Siga o roteiro proposto e vá completando as células vazias. Procure pensar em mais informações interessantes que podem ser exploradas em nosso dataset.

# <font color=green>DATASET DO PROJETO</font>
***

### Pesquisa Nacional por Amostra de Domicílios - 2015

A <b>Pesquisa Nacional por Amostra de Domicílios - PNAD</b> investiga anualmente, de forma permanente, características gerais da população, de educação, trabalho, rendimento e habitação e outras, com periodicidade variável, de acordo com as necessidades de informação para o país, como as características sobre migração, fecundidade, nupcialidade, saúde, segurança alimentar, entre outros temas. O levantamento dessas estatísticas constitui, ao longo dos 49 anos de realização da pesquisa, um importante instrumento para formulação, validação e avaliação de políticas orientadas para o desenvolvimento socioeconômico e a melhoria das condições de vida no Brasil.

### Fonte dos Dados

https://ww2.ibge.gov.br/home/estatistica/populacao/trabalhoerendimento/pnad2015/microdados.shtm

### Variáveis utilizadas

> ### Renda
> ***

Rendimento mensal do trabalho principal para pessoas de 10 anos ou mais de idade.

> ### Idade
> ***

Idade do morador na data de referência em anos.

> ### Altura (elaboração própria)
> ***

Altura do morador em metros.

> ### UF
> ***

|Código|Descrição|
|---|---|
|11|Rondônia|
|12|Acre|
|13|Amazonas|
|14|Roraima|
|15|Pará|
|16|Amapá|
|17|Tocantins|
|21|Maranhão|
|22|Piauí|
|23|Ceará|
|24|Rio Grande do Norte|
|25|Paraíba|
|26|Pernambuco|
|27|Alagoas|
|28|Sergipe|
|29|Bahia|
|31|Minas Gerais|
|32|Espírito Santo|
|33|Rio de Janeiro|
|35|São Paulo|
|41|Paraná|
|42|Santa Catarina|
|43|Rio Grande do Sul|
|50|Mato Grosso do Sul|
|51|Mato Grosso|
|52|Goiás|
|53|Distrito Federal|

> ### Sexo	
> ***

|Código|Descrição|
|---|---|
|0|Masculino|
|1|Feminino|

> ### Anos de Estudo
> ***

|Código|Descrição|
|---|---|
|1|Sem instrução e menos de 1 ano|
|2|1 ano|
|3|2 anos|
|4|3 anos|
|5|4 anos|
|6|5 anos|
|7|6 anos|
|8|7 anos|
|9|8 anos|
|10|9 anos|
|11|10 anos|
|12|11 anos|
|13|12 anos|
|14|13 anos|
|15|14 anos|
|16|15 anos ou mais|
|17|Não determinados| 
||Não aplicável|

> ### Cor
> ***

|Código|Descrição|
|---|---|
|0|Indígena|
|2|Branca|
|4|Preta|
|6|Amarela|
|8|Parda|
|9|Sem declaração|

#### <font color='red'>Observação</font>
***
> Os seguintes tratamentos foram realizados nos dados originais:
> 1. Foram eliminados os registros onde a <b>Renda</b> era inválida (999 999 999 999);
> 2. Foram eliminados os registros onde a <b>Renda</b> era missing;
> 3. Foram considerados somente os registros das <b>Pessoas de Referência</b> de cada domicílio (responsável pelo domicílio).

***
***

### Utilize a célula abaixo para importar as biblioteca que precisar para executar as tarefas
#### <font color='red'>Sugestões: pandas, numpy, seaborn</font>
"""

import pandas as pd
import numpy as np
import seaborn as sns

"""### Importe o dataset e armazene o conteúdo em uma DataFrame"""

from google.colab import files
uploaded = files.upload()

"""### Visualize o conteúdo do DataFrame"""

dados = pd.read_csv('dados.csv')
dados

"""### Para avaliarmos o comportamento da variável RENDA vamos construir uma tabela de frequências considerando as seguintes classes em salários mínimos (SM)
#### <font color='blue'>Descreva os pontos mais relevantes que você observa na tabela e no gráfico.</font>

Classes de renda:

<b>A</b> ► Acima de 25 SM

<b>B</b> ► De 15 a 25 SM

<b>C</b> ► De 5 a 15 SM

<b>D</b> ► De 2 a 5 SM

<b>E</b> ► Até 2 SM

Para construir as classes de renda considere que o salário mínimo na época da pesquisa era de <b>R$ 788,00</b>.

#### Siga os passos abaixo:

### 1º Definir os intevalos das classes em reais (R$)
"""

classes = [dados.Renda.min(), 1576, 3940, 11829, 19789, dados.Renda.max()]

"""### 2º Definir os labels das classes"""

labels = ['E', 'D', 'C', 'B', 'A']

"""### 3º Construir a coluna de frequências"""

frequencia = pd.value_counts(
                pd.cut(x = dados.Renda, 
                  bins = classes,
                  labels = labels,
                  include_lowest = True))
frequencia

"""### 4º Construir a coluna de percentuais"""

percentual = pd.value_counts(
  pd.cut(x = dados.Renda, 
    bins = classes,
    labels = labels,
    include_lowest = True),
  normalize = True
  ) * 100
percentual

"""### 5º Juntar as colunas de frequência e percentuais e ordenar as linhas de acordo com os labels das classes"""

dist_freq_quantitativas_personalizadas = pd.DataFrame(
    {'Frequência': frequencia, 'Porcentagem (%)': percentual}
)
dist_freq_quantitativas_personalizadas.sort_index(ascending = False, inplace = True)
dist_freq_quantitativas_personalizadas

"""### Construa um gráfico de barras para visualizar as informações da tabela de frequências acima"""

ax = dist_freq_quantitativas_personalizadas['Frequência'].plot.bar(width = 1, color = "blue", alpha = 0.2, figsize = (14,6))
ax.set_title('Distribuição de Frequências - Renda', fontsize=18)
ax.set_xlabel('R$', fontsize=14)
ax

"""> ### Conclusões

A partir da visualização gráfica da variável Renda é possível inferir que a maior parte da amostra se encontra recebendo mensalmente em torno de um salário minímo (64%), enquanto menos de 1% (0,54%) recebe acima de 25 salários minímos.

### Crie um histograma para as variáveis QUANTITATIVAS de nosso dataset
#### <font color='blue'>Descreva os pontos mais relevantes que você observa nos gráficos (assimetrias e seus tipos, possíveis causas para determinados comportamentos etc.)</font>
"""

ax = sns.distplot(dados.Altura)

ax.figure.set_size_inches(12, 6)
ax.set_title('Distribuição de Frequências - Altura', fontsize=18)
ax.set_xlabel('Metros', fontsize=14)
ax

bx = sns.distplot(dados.Idade)

bx.figure.set_size_inches(12, 6)
bx.set_title('Distribuição de Frequências - Idade', fontsize=18)
bx.set_xlabel('Anos', fontsize=14)
bx



"""> ### Conclusões

Os histogramas das variáveis altura e idade nos indicam o comportamento dessas variáveis, como por exemplo é possível perceber que a variável Altura possui simetria enquanto a variável Idade possui simetria para a direita.

### Para a variável RENDA, construa um histograma somente com as informações das pessoas com rendimento até R$ 20.000,00
"""

ax = sns.distplot(dados.query('Renda < 20000').Renda)
ax.figure.set_size_inches(14, 6)
ax.set_title('Distribuição Frequência de pessoas com renda até R$20.000,00')
ax.set_xlabel('R$', fontsize = 12)
ax

"""### Construa uma tabela de frequências e uma com os percentuais do cruzando das variáveis SEXO e COR
#### <font color='blue'>Avalie o resultado da tabela e escreva suas principais conclusões</font>
#### <font color='red'>Utilize os dicionários abaixo para renomear as linha e colunas das tabelas de frequências e dos gráficos em nosso projeto</font>
"""

sexo = {
    0: 'Masculino', 
    1: 'Feminino'
}
cor = {
    0: 'Indígena', 
    2: 'Branca', 
    4: 'Preta', 
    6: 'Amarela', 
    8: 'Parda', 
    9: 'Sem declaração'
}
anos_de_estudo = {
    1: 'Sem instrução e menos de 1 ano', 
    2: '1 ano', 
    3: '2 anos', 
    4: '3 anos', 
    5: '4 anos', 
    6: '5 anos', 
    7: '6 anos', 
    8: '7 anos', 
    9: '8 anos', 
    10: '9 anos', 
    11: '10 anos', 
    12: '11 anos', 
    13: '12 anos', 
    14: '13 anos', 
    15: '14 anos', 
    16: '15 anos ou mais', 
    17: 'Não determinados'
}
uf = {
    11: 'Rondônia', 
    12: 'Acre', 
    13: 'Amazonas', 
    14: 'Roraima', 
    15: 'Pará', 
    16: 'Amapá', 
    17: 'Tocantins', 
    21: 'Maranhão', 
    22: 'Piauí', 
    23: 'Ceará', 
    24: 'Rio Grande do Norte', 
    25: 'Paraíba', 
    26: 'Pernambuco', 
    27: 'Alagoas', 
    28: 'Sergipe', 
    29: 'Bahia', 
    31: 'Minas Gerais', 
    32: 'Espírito Santo', 
    33: 'Rio de Janeiro', 
    35: 'São Paulo', 
    41: 'Paraná', 
    42: 'Santa Catarina', 
    43: 'Rio Grande do Sul', 
    50: 'Mato Grosso do Sul', 
    51: 'Mato Grosso', 
    52: 'Goiás', 
    53: 'Distrito Federal'
}

frequencia = pd.crosstab(dados.Sexo, 
                         dados.Cor)
frequencia.rename(index = sexo, inplace = True)
frequencia.rename(columns = cor, inplace = True)
frequencia

percentual = pd.crosstab(dados.Sexo, 
                         dados.Cor,
                         normalize = True) * 100
percentual.rename(index = sexo, inplace = True)
percentual.rename(columns = cor, inplace = True)
percentual

"""> ### Conclusões

Esse tipo de visualização (crosstab) é interessante porque permite a junção de dados de duas variavéis possibilitando uma visualização de dados com informações "novas" e mais precisas. Nesse exemplo é interessante perceber a porcentagem de chefes da família que se declararam de qual cor e o que isso diz sobre a amostra e sobre o país. Esses dados também nos permitem fazer mais analises para comparar qual a renda média de cada cor por genêro.

## Realize, para a variável RENDA, uma análise descritiva com as ferramentas que aprendemos em nosso treinamento

### Obtenha a média aritimética
"""

dados['Renda'].mean()

"""### Obtenha a mediana"""

dados['Renda'].median()

"""### Obtenha a moda"""

dados.Renda.mode()

"""### Obtenha o desvio médio absoluto"""

dados.Renda.mad()

"""### Obtenha a variância"""

dados['Renda'].var()

"""### Obtenha o desvio-padrão"""

dados.Renda.std()

"""### Obtenha a média, mediana e valor máximo da variável RENDA segundo SEXO e COR
#### <font color='blue'>Destaque os pontos mais importante que você observa nas tabulações</font>
#### <font color='red'>O parâmento <i>aggfunc</i> da função <i>crosstab()</i> pode receber uma lista de funções. Exemplo: <i>aggfunc = {'mean', 'median', 'max'}</i></font>
"""

renda = pd.crosstab(dados.Sexo, 
                         dados.Cor,
                         aggfunc = {'mean', 'median', 'max'},
                         values = dados.Renda)
renda.rename(index = sexo, inplace = True)
renda.rename(columns = cor, inplace = True)
renda

"""> ### Conclusões

Nesse exemplo ao analisar a variável renda é possível inferir que pessoas autodeclaradas indígenas, pretas e pardas possuem em média renda menor do que aquelas declaradas brancas e amarelas, e se compararmos com a tabela anterior mostrando frequência é possível perceber que pessoas pretas e partas compõem a maior frequência dentro da amostra e mesmo assim possuem média salarial menor se comparado com pessoas brancas e amarelas. 
"""



"""### Obtenha as medidas de dispersão da variável RENDA segundo SEXO e COR
#### <font color='blue'>Destaque os pontos mais importante que você observa nas tabulações</font>
#### <font color='red'>O parâmento <i>aggfunc</i> da função <i>crosstab()</i> pode receber uma lista de funções. Exemplo: <i>aggfunc = {'mad', 'var', 'std'}</i></font>
"""

renda = pd.crosstab(dados.Sexo, 
                         dados.Cor,
                         aggfunc = {'mad', 'var', 'std'},
                         values = dados.Renda)
renda.rename(index = sexo, inplace = True)
renda.rename(columns = cor, inplace = True)
renda

"""> ### Conclusões

Escreva suas conclusões aqui...

### Construa um box plot da variável RENDA segundo SEXO e COR
#### <font color='blue'>É possível verificar algum comportamento diferenciado no rendimento entre os grupos de pessoas analisados? Avalie o gráfico e destaque os pontos mais importantes.</font>
#### <font color='red'>1º - Utilize somente as informações de pessoas com renda abaixo de R$ 10.000</font>
#### <font color='red'>2º - Para incluir uma terceira variável na construção de um boxplot utilize o parâmetro <i>hue</i> e indique a variável que quer incluir na subdivisão.</font>
#### Mais informações: https://seaborn.pydata.org/generated/seaborn.boxplot.html
"""

ax = sns.boxplot(x = 'Renda', y = 'Sexo', hue = 'Cor', data = dados.query("Renda < 10000"), orient = 'h')
ax.figure.set_size_inches(20, 8)
ax.set_title('Renda por Cor e Sexo', fontsize=18)
ax.set_xlabel('R$', fontsize=14)
ax.set_ylabel('Sexo', fontsize = 14)
ax.set_yticklabels(['Homens', 'Mulheres'], fontsize = 12)
legend_label = ["Indígena", "Branca", "Preta", "Amarela", "Parda"]
n = 0
for i in legend_label:
    ax.legend_.texts[n].set_text(i)
    n += 1
ax

"""> ### Conclusões

Escreva suas conclusões aqui...

# <font color="red">DESAFIO<font>
### Qual percentual de pessoas de nosso <i>dataset</i> ganham um salário mínimo (R$ 788,00) ou menos?
#### <font color='red'>Utilize a função <i>percentileofscore()</i> do <i>scipy</i> para realizar estas análises.</font>
#### Mais informações: https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.percentileofscore.html
"""

from scipy import stats

percentual = stats.percentileofscore(dados.Renda, 788, kind = 'weak') #o parametro weak inclui o valor limite, nesse caso 788
print(f'Percentual de pessoas que recebem até um salário mínimo: {percentual :.2f}%')

"""### Qual o valor máximo ganho por 99% das pessoas de nosso <i>dataset</i>?
#### <font color='red'>Utilize o método <i>quantile()</i> do <i>pandas</i> para realizar estas análises.</font>
"""

valor = dados.Renda.quantile(.99)
print(f'Valor maxímo ganho por 99% das pessoas: {valor :.2f}')

"""### Obtenha a média, mediana, valor máximo e desvio-padrão da variável RENDA segundo ANOS DE ESTUDO e SEXO
#### <font color='blue'>Destaque os pontos mais importante que você observa nas tabulações</font>
#### <font color='red'>O parâmento <i>aggfunc</i> da função <i>crosstab()</i> pode receber uma lista de funções. Exemplo: <i>aggfunc = ['mean', 'median', 'max', 'std']</i></font>
"""

renda_por_sexo_e_estudo = pd.crosstab(dados['Anos de Estudo'],
                                      dados.Sexo, 
                                      aggfunc = {'mean', 'median', 'max', 'std'},
                                      values = dados.Renda).round(2)
renda_por_sexo_e_estudo.rename(index = anos_de_estudo, inplace = True)
renda_por_sexo_e_estudo.rename(columns = sexo, inplace = True)
renda_por_sexo_e_estudo

"""### Construa um box plot da variável RENDA segundo ANOS DE ESTUDO e SEXO
#### <font color='blue'>É possível verificar algum comportamento diferenciado no rendimento entre os grupos de pessoas analisados? Avalie o gráfico e destaque os pontos mais importantes.</font>
#### <font color='red'>1º - Utilize somente as informações de pessoas com renda abaixo de R$ 10.000</font>
#### <font color='red'>2º - Utilize a variável IDADE para identificar se a desigualdade se verifica para pessoas de mesma idade. Exemplo: <i>data=dados.query('Renda < 10000 and Idade == 40')</i> ou <i>data=dados.query('Renda < 10000 and Idade == 50')</i></font>
#### <font color='red'>3º - Para incluir uma terceira variável na construção de um boxplot utilize o parâmetro <i>hue</i> e indique a variável que quer incluir na subdivisão.</font>
#### Mais informações: https://seaborn.pydata.org/generated/seaborn.boxplot.html
"""

ax = sns.boxplot(x = 'Renda', y = 'Anos de Estudo', hue = 'Sexo', data = dados.query('Renda < 10000 and Idade == 50'), orient = 'h')
ax.figure.set_size_inches(14, 8)
ax.set_title('Renda por Anos de Estudo e Sexo', fontsize = 18)
ax.set_xlabel('R$', fontsize = 14)
ax.set_ylabel('Anos de Estudo', fontsize = 14)
ax.set_yticklabels([key for key in anos_de_estudo.values()], fontsize = 12)
handles, _ = ax.get_legend_handles_labels()
ax.legend(handles, ['Masculino', 'Feminino'], fontsize = 12)
ax

"""> ### Conclusões:

A análise do gráfico acima pode indicar que com o aumento dos anos de escolaridade existe uma crescente no valor da renda mensal também.

### Obtenha a média, mediana, valor máximo e desvio-padrão da variável RENDA segundo as UNIDADES DA FEDERAÇÃO
#### <font color='blue'>Destaque os pontos mais importante que você observa nas tabulações</font>
#### <font color='red'>Utilize o método <i>groupby()</i> do <i>pandas</i> juntamente com o método <i>agg()</i> para contruir a tabulação. O método <i>agg()</i> pode receber um dicionário especificando qual coluna do DataFrame deve ser utilizada e qual lista de funções estatísticas queremos obter, por exemplo: <i>dados.groupby(['UF']).agg({'Renda': ['mean', 'median', 'max', 'std']})</i></font>
"""

renda_por_uf = dados.groupby(['UF']).agg({'Renda': ['mean', 'median', 'max', 'std']})
renda_por_uf.rename(index = uf)

"""### Construa um box plot da variável RENDA segundo as UNIDADES DA FEDERAÇÃO
#### <font color='blue'>É possível verificar algum comportamento diferenciado no rendimento entre os grupos analisados? Avalie o gráfico e destaque os pontos mais importantes.</font>
#### <font color='red'>1º - Utilize somente as informações de pessoas com renda abaixo de R$ 10.000</font>
"""

ax = sns.boxplot(x = 'Renda', y = 'UF', data = dados.query('Renda < 10000'), orient = 'h')
ax.figure.set_size_inches(14, 8)
ax.set_title('Renda por estados', fontsize = 18)
ax.set_xlabel('R$', fontsize = 14)
ax.set_ylabel('Estados', fontsize = 14)
ax.set_yticklabels([key for key in uf.values()], fontsize = 12)
ax

"""> ### Conclusões

Escreva suas conclusões aqui...
"""